name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # Setting an environment variable with the value of a configuration variable
  SECRET_KEY: ${{ vars.SECRET_KEY }}
  STATIC_ROOT: ${{ vars.STATIC_ROOT }}
  DEBUG: ${{ vars.DEBUG }}
  BOT_TOKEN: ${{ vars.BOT_TOKEN }}
  CHAT_ID: ${{ vars.CHAT_ID }}
  DB_NAME: ${{ vars.DB_NAME }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASS: ${{ vars.DB_PASS }}
  DB_HOST: ${{ vars.DB_HOST }}

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Run migrations & collectstatic
      run: |
        printf "SECRET_KEY=$SECRET_KEY\nSTATIC_ROOT=$STATIC_ROOT\nDEBUG=$DEBUG\nBOT_TOKEN=$BOT_TOKEN\nCHAT_ID=$CHAT_ID\nDB_NAME=$DB_NAME\nDB_USER=$DB_USER\nDB_PASS=$DB_PASS\nDB_HOST=$DB_HOST" > .env
        pip install -r r.txt
        python3 manage.py migrate
        python3 manage.py collectstatic --noinput
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Restart supervisor
        run: |
          printf "SECRET_KEY=$SECRET_KEY\nSTATIC_ROOT=$STATIC_ROOT\nDEBUG=$DEBUG\nBOT_TOKEN=$BOT_TOKEN\nCHAT_ID=$CHAT_ID\nDB_NAME=$DB_NAME\nDB_USER=$DB_USER\nDB_PASS=$DB_PASS\nDB_HOST=$DB_HOST" > .env
          supervisorctl restart store
          supervisorctl status store

    
