# Generated by Django 5.0.6 on 2024-05-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productproperty_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_preview',
        ),
    ]
