# Generated by Django 5.0.6 on 2024-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_baseproperty_alter_productproperty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='name_ru',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Наименование (ru)'),
        ),
    ]
