# Generated by Django 5.0.6 on 2024-05-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
