# Generated by Django 5.0.6 on 2024-05-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='phone',
            field=models.CharField(default=79999999999, max_length=256, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
