# Generated by Django 5.0.6 on 2024-05-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_orderproduct_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Количество'),
        ),
    ]
