# Generated by Django 5.0.6 on 2024-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=79999999999, max_length=256, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
