# Generated by Django 5.0.6 on 2024-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Наименование (en)'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='name_ru',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Наименование (ru)'),
        ),
    ]
