# Generated by Django 5.0.6 on 2024-05-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_productimage_is_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True, verbose_name='Наименование (en)')),
                ('name_ru', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True, verbose_name='Наименование (ru)')),
                ('units', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ед. изм.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='units',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='base_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.baseproperty', verbose_name='Характеристика'),
        ),
    ]
