# Generated by Django 5.0.6 on 2024-05-12 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_baseproperty_name_ru'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
                ('street', models.CharField(max_length=256, verbose_name='Улица')),
                ('house', models.CharField(max_length=256, verbose_name='Дом')),
                ('entrance', models.CharField(blank=True, max_length=256, null=True, verbose_name='Подъезд')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Подъезд')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'unique_together': {('user', 'city', 'street', 'house', 'entrance')},
            },
        ),
    ]
