# Generated by Django 5.0.6 on 2024-05-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Товар заказа', 'verbose_name_plural': 'Товары заказов'},
        ),
    ]
