# Generated by Django 5.0.6 on 2024-05-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Имя', max_length=256, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
